# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-03 17:01
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0029_auto_20190203_1701'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('viber', 'Viber'), ('whatsapp', 'Whatsapp'), ('skype', 'Skype'), ('facebook_messenger', 'Facebook Messenger')], default=None, max_length=20, null=True)),
                ('text', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('index', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterEmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('value', ckeditor.fields.RichTextField(blank=True)),
                ('type', models.CharField(choices=[('service_base', 'service_base'), ('service_confirmation', 'service_base'), ('service_reminder', 'service_base'), ('service_thanks', 'service_base')], default='service_base', max_length=20, verbose_name='type')),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfirmationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('pending_reminder', 'Pending after reminder'), ('pending_unconfirmed_reminder', 'Pending after unconfirmed reminder'), ('outdated', 'Service needs update'), ('error', 'Error occurred during email sending'), ('focal_point_added', 'Focal point added')], max_length=255, null=True)),
                ('sent_to', models.EmailField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='tag name')),
            ],
        ),
        migrations.CreateModel(
            name='TypesOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='service',
            name='area_of_service',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lebanon_region',
        ),
        migrations.AddField(
            model_name='nationality',
            name='name_el',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name in Greek'),
        ),
        migrations.AddField(
            model_name='nationality',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name in Spanish'),
        ),
        migrations.AddField(
            model_name='nationality',
            name='name_ti',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name in Tigrinya'),
        ),
        migrations.AddField(
            model_name='nationality',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name in Urdu'),
        ),
        migrations.AddField(
            model_name='provider',
            name='additional_info',
            field=models.TextField(blank=True, default='', verbose_name='additional_info'),
        ),
        migrations.AddField(
            model_name='provider',
            name='address_el',
            field=models.TextField(blank=True, default='', verbose_name='provider address in Greek'),
        ),
        migrations.AddField(
            model_name='provider',
            name='address_es',
            field=models.TextField(blank=True, default='', verbose_name='provider address in Spanish'),
        ),
        migrations.AddField(
            model_name='provider',
            name='address_ti',
            field=models.TextField(blank=True, default='', verbose_name='provider address in Tigrinya'),
        ),
        migrations.AddField(
            model_name='provider',
            name='address_ur',
            field=models.TextField(blank=True, default='', verbose_name='provider address in Urdu'),
        ),
        migrations.AddField(
            model_name='provider',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='contact_name'),
        ),
        migrations.AddField(
            model_name='provider',
            name='description_el',
            field=models.TextField(blank=True, default='', verbose_name='description in Greek'),
        ),
        migrations.AddField(
            model_name='provider',
            name='description_es',
            field=models.TextField(blank=True, default='', verbose_name='description in Spanish'),
        ),
        migrations.AddField(
            model_name='provider',
            name='description_ti',
            field=models.TextField(blank=True, default='', verbose_name='description in Tigrinya'),
        ),
        migrations.AddField(
            model_name='provider',
            name='description_ur',
            field=models.TextField(blank=True, default='', verbose_name='description in Urdu'),
        ),
        migrations.AddField(
            model_name='provider',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='provider',
            name='focal_point_name_el',
            field=models.CharField(blank=True, default='', max_length=256, validators=[services.models.blank_or_at_least_one_letter], verbose_name='focal point name in Greek'),
        ),
        migrations.AddField(
            model_name='provider',
            name='focal_point_name_es',
            field=models.CharField(blank=True, default='', max_length=256, validators=[services.models.blank_or_at_least_one_letter], verbose_name='focal point name in Spanish'),
        ),
        migrations.AddField(
            model_name='provider',
            name='focal_point_name_ti',
            field=models.CharField(blank=True, default='', max_length=256, validators=[services.models.blank_or_at_least_one_letter], verbose_name='focal point name in Tigrinya'),
        ),
        migrations.AddField(
            model_name='provider',
            name='focal_point_name_ur',
            field=models.CharField(blank=True, default='', max_length=256, validators=[services.models.blank_or_at_least_one_letter], verbose_name='focal point name in Urdu'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='is frozen'),
        ),
        migrations.AddField(
            model_name='provider',
            name='meta_population',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='meta_population'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_el',
            field=models.CharField(blank=True, default='', max_length=256, validators=[services.models.blank_or_at_least_one_letter], verbose_name='Name in Greek'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=256, validators=[services.models.blank_or_at_least_one_letter], verbose_name='Name in Spanish'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_ti',
            field=models.CharField(blank=True, default='', max_length=256, validators=[services.models.blank_or_at_least_one_letter], verbose_name='Name in Tigrinya'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, validators=[services.models.blank_or_at_least_one_letter], verbose_name='Name in Urdu'),
        ),
        migrations.AddField(
            model_name='provider',
            name='record',
            field=models.TextField(blank=True, default='', verbose_name='record'),
        ),
        migrations.AddField(
            model_name='provider',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='regions.GeographicRegion', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='provider',
            name='requirement',
            field=models.TextField(blank=True, default='', verbose_name='requirement'),
        ),
        migrations.AddField(
            model_name='provider',
            name='service_types',
            field=models.ManyToManyField(blank=True, to='services.ServiceType', verbose_name='service_types'),
        ),
        migrations.AddField(
            model_name='provider',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='providers', to=settings.AUTH_USER_MODEL, verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='provider',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='provider',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='twitter'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vacancy',
            field=models.BooleanField(default=False, verbose_name='vacancy'),
        ),
        migrations.AddField(
            model_name='providertype',
            name='name_el',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Greek'),
        ),
        migrations.AddField(
            model_name='providertype',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Spanish'),
        ),
        migrations.AddField(
            model_name='providertype',
            name='name_ti',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Tigrinya'),
        ),
        migrations.AddField(
            model_name='providertype',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Urdu'),
        ),
        migrations.AddField(
            model_name='selectioncriterion',
            name='text_el',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='selectioncriterion',
            name='text_es',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='selectioncriterion',
            name='text_ti',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='selectioncriterion',
            name='text_ur',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_info_el',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Greek'),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_info_es',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Spanish'),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_info_ti',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Tigrinya'),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_info_ur',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Arabic'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Arabic'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in German'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_el',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Greek'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in English'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Spanish'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_fa',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Persian'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in French'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_ti',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Tigrinya'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_ur',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in German'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_el',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Greek'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in English'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Spanish'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_fa',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Persian'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_el',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_ti',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in French'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_in_country_language',
            field=models.TextField(blank=True, null=True, verbose_name='Address in country language'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_ti',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Tigrinya'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_ur',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='confirmation_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_el',
            field=models.TextField(blank=True, default='', verbose_name='Description in Greek'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.TextField(blank=True, default='', verbose_name='Description in Spanish'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ti',
            field=models.TextField(blank=True, default='', verbose_name='Description in Tigrinya'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ur',
            field=models.TextField(blank=True, default='', verbose_name='Description in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='service',
            name='exclude_from_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='facebook_page',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Link to facebook page'),
        ),
        migrations.AddField(
            model_name='service',
            name='focal_point_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='focal_point_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='focal_point_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='focal_point_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='foreign_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_ar',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Arabic'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_de',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in German'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_el',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Greek'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_en',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in English'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_es',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Spanish'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_fa',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Persian'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_fr',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in French'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_ti',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Tigrinya'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_ur',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_el',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Greek'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Spanish'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ti',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Tigrinya'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='newsletter_valid_emails',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='opening_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Use ISO phone numbers with no spaces, ex: +3815551234', max_length=40, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='service',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='regions.GeographicRegion', verbose_name='area of service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='second_focal_point_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='second_focal_point_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='second_focal_point_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='second_focal_point_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(help_text='This field has to be unique', max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='types',
            field=models.ManyToManyField(blank=True, to='services.ServiceType', verbose_name='types'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='service',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Whatsapp number'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='geographic_region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.GeographicRegion'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='name_el',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Greek'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Spanish'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='name_ti',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Tigrinya'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Urdu'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='comments_el',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='comments in Greek'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='comments_es',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='comments in Spanish'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='comments_ti',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='comments in Tigrinya'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='comments_ur',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='comments in Urdu'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_el',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name in Greek'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name in Spanish'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_ti',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name in Tigrinya'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name in Urdu'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='vector_icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vector Icon'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='area_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceArea', verbose_name='Area of residence'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='delivered',
            field=models.NullBooleanField(default=False, help_text='Was service delivered?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='focal_point_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='focal point phone number'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_providers', to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_ar',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Arabic'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_de',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in German'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_en',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in English'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_fa',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Persian'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_fr',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in French'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Description in Arabic'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='Description in German'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description in English'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_fa',
            field=models.TextField(blank=True, default='', verbose_name='Description in Persian'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_fr',
            field=models.TextField(blank=True, default='', verbose_name='Description in French'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Arabic'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in German'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in English'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_fa',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Persian'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in French'),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.Provider', verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('current', 'current'), ('rejected', 'rejected'), ('canceled', 'canceled'), ('archived', 'archived'), ('private', 'private')], default='draft', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='services.ServiceType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GeographicRegion',
        ),
        migrations.AddField(
            model_name='usernote',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.Service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='typesordering',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.GeographicRegion'),
        ),
        migrations.AddField(
            model_name='typesordering',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType'),
        ),
        migrations.AddField(
            model_name='serviceconfirmationlog',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_logs', to='services.Service'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_information', to='services.Service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Specific tags for this service.', to='services.ServiceTag', verbose_name='service tags'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='ordering',
            field=models.ManyToManyField(blank=True, through='services.TypesOrdering', to='regions.GeographicRegion', verbose_name='ordering'),
        ),
    ]
