# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-17 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190203_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('viber', 'Viber'), ('whatsapp', 'Whatsapp'), ('skype', 'Skype'), ('facebook_messenger', 'Facebook Messenger'), ('instagram', 'Instagram')], default=None, max_length=20, null=True),
        ),
    ]
