# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20160403_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
