# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_servicetype_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='area_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceArea', verbose_name='Area of residence'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='delivered',
            field=models.NullBooleanField(default=False, help_text='Was service delivered?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
