# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20160509_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='vector_icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vector Icon'),
        ),
    ]
