# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_servicetype_vector_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address in Arabic'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address in German'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_el',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address in Greek'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address in English'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address in Spanish'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_fa',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address in Persian'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address in French'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_ar',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Arabic'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_de',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in German'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_el',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Greek'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_en',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in English'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_es',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Spanish'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_fa',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Persian'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_info_fr',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in French'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Description in Arabic'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='Description in German'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_el',
            field=models.TextField(blank=True, default='', verbose_name='Description in Greek'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description in English'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_es',
            field=models.TextField(blank=True, default='', verbose_name='Description in Spanish'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_fa',
            field=models.TextField(blank=True, default='', verbose_name='Description in Persian'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_fr',
            field=models.TextField(blank=True, default='', verbose_name='Description in French'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Arabic'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in German'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_el',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Greek'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in English'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Spanish'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_fa',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Persian'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in French'),
        ),
    ]
