# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20160722_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Use ISO phone numbers with no spaces, ex: +3815551234', max_length=40, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(help_text='user account for this provider', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
