# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models


def no_op(apps, schema_editor):
    pass


def create_external_provider(apps, schema_editor):
    ProviderType = apps.get_model('services', 'ProviderType')
    all_provider_types = ProviderType.objects.all()
    externals = ProviderType.objects.filter(name_en='External source')
    if not externals:
        provider_number = max(provider_type.number for provider_type in all_provider_types) + 1\
            if all_provider_types else 0
        ProviderType.objects.create(
            number=provider_number,
            name_en='External source'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20160728_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='clinic_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=create_external_provider,
            reverse_code=no_op,
            atomic=True
        )
    ]
