# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_service_clinic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
