# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 19:29
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models, transaction


class Migration(migrations.Migration):
    dependencies = [
        ('regions', '0024_auto_20170201_1929'),
        ('services', '0019_service_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='regions.GeographicRegion', verbose_name='area of service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services',
                                    to='services.Provider', verbose_name='provider'),
        ),
    ]
