# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 19:29
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models, transaction


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0020_auto_20170201_1929'),
    ]

    def update_regions(apps, schema_editor):
        Service = apps.get_model('services', 'service')
        for row in Service.objects.all():
            row.region = row.area_of_service.geographic_region
            row.save()

    operations = [
        migrations.RunPython(update_regions)
    ]
