# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_update_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='area_of_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceArea', verbose_name='area of service'),
        ),
    ]
