# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0022_auto_20170201_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='providers', to=settings.AUTH_USER_MODEL, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_providers', to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
    ]
