# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20170201_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='area_of_service',
        ),
    ]
