# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-05 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_remove_service_area_of_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='clinic_id',
            new_name='foreign_object_id',
        ),
    ]
