# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-05 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_auto_20170305_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
