# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import re


def generate_slug(region_slug, provider_id, service_name):
    print('Generating new slug for: {}'.format(service_name))
    service_name = service_name.replace(' ', '-')
    # Remove ALL NON hyphen/alphanumerical/underscore characters
    name = re.sub('[^-a-zA-Z0-9_]', '', service_name)
    slug = '_'.join((region_slug, str(provider_id), name))
    return slug


def forwards_func(apps, schema_editor):
    service_model = apps.get_model('services', 'Service')
    services = service_model.objects.filter(slug=None)
    for service in services:
        # generate slug with pattern: regionSLUG_providerID_serviceNAME
        new_slug = generate_slug(service.region.slug, service.provider_id, service.name_en)
        # Check if given slug exists, if yes then add service id at the end
        if len(service_model.objects.filter(slug=new_slug)) > 0:
            new_slug = new_slug + '_' + str(service.id)
        service.slug = new_slug
        service.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20170305_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True, null=True, help_text='This field has to be unique', max_length=512),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
