# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address_in_country_language',
            field=models.TextField(blank=True, null=True, verbose_name='Address in country language'),
        ),
    ]
