# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_auto_20170309_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providertype',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
