# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-15 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20170310_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='service',
            name='facebook_page',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Link to facebook page'),
        ),
        migrations.AddField(
            model_name='service',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='website'),
        ),
    ]
