# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_auto_20170315_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
