# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_servicetype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address_city_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Arabic'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in German'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_el',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Greek'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in English'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Spanish'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_fa',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Persian'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in French'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='address_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Arabic'),
        ),
        migrations.AlterField(
            model_name='service',
            name='address_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in German'),
        ),
        migrations.AlterField(
            model_name='service',
            name='address_el',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Greek'),
        ),
        migrations.AlterField(
            model_name='service',
            name='address_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in English'),
        ),
        migrations.AlterField(
            model_name='service',
            name='address_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Spanish'),
        ),
        migrations.AlterField(
            model_name='service',
            name='address_fa',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Persian'),
        ),
        migrations.AlterField(
            model_name='service',
            name='address_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in French'),
        ),
    ]
