# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_service_opening_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='address_floor',
            new_name='address_floor_en',
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_el',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='focal_point_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='focal_point_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='focal_point_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
