# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-07 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_auto_20170519_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfirmationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('pending_reminder', 'Pending after reminder'), ('outdated', 'Service needs update')], max_length=255, null=True)),
                ('confirmed_by', models.EmailField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='confirmation_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='exclude_from_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceconfirmationlog',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_logs', to='services.Service'),
        ),
    ]
