# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    service_model = apps.get_model('services', 'Service')
    services = service_model.objects.filter(created_at=None)
    for service in services:
        service.created_at = service.updated_at
        service.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_auto_20170607_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
