# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_auto_20170630_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='newsletter_valid_email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
