# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 13:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
from services.models import NewsletterEmailTemplate


INITIAL_EMAIL_HTML_INSERTS = [
    dict(
        name='base_footer_header',
        label='Footer header text',
        value='<p dir="ltr" style="text-align: center; font-size: 20px; font-style: normal; font-weight: bold;"> \
               THE REFUGEE.INFO PROJECT</p>',
        type=NewsletterEmailTemplate.SERVICE_BASE,
        order=1
    ),
    dict(
        name='base_footer_mailing_adress',
        label='Footer mailing address',
        value='<strong>Our mailing address is:</strong><br>servicemap@refugee.info',
        type=NewsletterEmailTemplate.SERVICE_BASE,
        order=2
    ),
    dict(
        name='confirmation_header_photo',
        label='Header photo',
        value='https://gallery.mailchimp.com/881109e97ad9515d9bad45d66/images/bd6ee6fd-eb3b-4cee-b96d-8195fe6222d4.png',
        type=NewsletterEmailTemplate.SERVICE_CONFIRMATION,
        order=1
    ),
    dict(
        name='confirmation_content_header',
        label='Content header text',
        value='<p dir="ltr" style="text-align: center; font-size: 20px; font-style: normal; \
               font-weight: bold; margin-top: 0px; margin-bottom: 10px;">SERVICE MAPPING UPDATE REQUEST</p>',
        type=NewsletterEmailTemplate.SERVICE_CONFIRMATION,
        order=2
    ),
    dict(
        name='confirmation_content_before_name_text',
        label='Content before name text',
        value='Dear ',
        type=NewsletterEmailTemplate.SERVICE_CONFIRMATION,
        order=3
    ),
    dict(
        name='confirmation_content_after_name_text',
        label='Content after name text',
        value=', ',
        type=NewsletterEmailTemplate.SERVICE_CONFIRMATION,
        order=4
    ),
    dict(
        name='confirmation_content_text_before_provider',
        label='Content before provider text',
        value='<br>Thank you again for providing information about ',
        type=NewsletterEmailTemplate.SERVICE_CONFIRMATION,
        order=5
    ),
    dict(
        name='confirmation_content_text_between_provider_service',
        label='Content between provider and service text',
        value='’s services for the ',
        type=NewsletterEmailTemplate.SERVICE_CONFIRMATION,
        order=6
    ),
    dict(
        name='confirmation_content_text_after_service',
        label='Content after service text',
        value=' service mapping on Refugee.Info.<br> \
                    <br> \
                    I’m getting in touch to make sure all your organization’s entries are up-to-date.<br> \
                    <br> \
                    Could you please take a moment to glance over your entries and \
                    let me know if I need to make any changes?</p> \
                    <br> \
                    <p dir="ltr" style="text-align: center; font-size: 17px; font-style: normal; font-weight: bold;"> \
                        YOUR ENTRIES ON REFUGEE.INFO \
                    </p>',
        type=NewsletterEmailTemplate.SERVICE_CONFIRMATION,
        order=7
    ),
    dict(
        name='confirmation_before_footer_text',
        label='Before footer text',
        value='  <p dir="ltr" style="text-align: left;font-family: Helvetica;"> \
                        If I don’t receive your \
                        reply in the next two weeks, I\'ll send a reminder. If I still \
                        haven’t heard from you a week after that, I will \
                        remove your services from the map until we have been in \
                        touch. \
                    </p> \
                    <p dir="ltr" style="text-align: left;font-family: Helvetica;"> \
                        If someone else should be the focal point for these entries, please \
                        reply to this mail to let me know. \
                    </p> \
                    <p dir="ltr" style="text-align: left;font-family: Helvetica; margin-top: 25px;"> \
                        Best wishes and greetings,<br> \
                        Elise <br> \
                        Service Mapping Editor, Refugee.Info \
                    </p>',
        type=NewsletterEmailTemplate.SERVICE_CONFIRMATION,
        order=8
    ),
    dict(
        name='reminder_header_photo',
        label='Header photo',
        value='https://gallery.mailchimp.com/881109e97ad9515d9bad45d66/images/c0184ea0-bd10-409d-8f1f-7274a3b4ab06.png',
        type=NewsletterEmailTemplate.SERVICE_REMINDER,
        order=1
    ),
    dict(
        name='reminder_content_header',
        label='Content header text',
        value='<p dir="ltr" style="text-align: center; font-size: 20px; font-style: normal;'
              ' font-weight: bold; margin-top: 0px; margin-bottom: 10px;">SERVICE MAPPING UPDATE REQUEST</p>',
        type=NewsletterEmailTemplate.SERVICE_REMINDER,
        order=2
    ),
    dict(
        name='reminder_content_before_name_text',
        label='Content before name text',
        value='Dear ',
        type=NewsletterEmailTemplate.SERVICE_REMINDER,
        order=3
    ),
    dict(
        name='reminder_content_after_name_text',
        label='Content after name text',
        value=', ',
        type=NewsletterEmailTemplate.SERVICE_REMINDER,
        order=4
    ),
    dict(
        name='reminder_content_text',
        label='Content main text',
        value='  <br> \
                    <br> \
                    I’m sending this message to remind you to let me know whether \
                    you’ve made any changes to the services you provide. <br> \
                    <br> \
                    In order to keep the map up-to-date and relevant to the people using it, \
                    we will take down service entries that have not been confirmed.<br> \
                    <br> \
                    Could you please take a moment to glance over your organization’s entries and \
                    let me know if any changes need to be made? </p> \
                    <br> \
                    <p dir="ltr" style="text-align: center; font-size: 17px; font-style: normal; font-weight: bold;"> \
                        YOUR ENTRIES ON REFUGEE.INFO \
                    </p>',
        type=NewsletterEmailTemplate.SERVICE_REMINDER,
        order=5
    ),
    dict(
        name='reminder_before_footer_text',
        label='Before footer text',
        value='  <p dir="ltr" style="text-align: left;font-family: Helvetica;"> \
                        If we don’t hear from you in the next week, we will remove your services from the map until we \
                        have been in touch. Please feel free to reach out to me at any time! \
                    </p> \
                    <p dir="ltr" style="text-align: left;font-family: Helvetica;"> \
                        If someone else should be the focal point for these entries, \
                        please reply to this email to let me know. \
                    </p> \
                    <p dir="ltr" style="text-align: left;font-family: Helvetica;"> \
                        Thank you again! \
                    </p> \
                    <p dir="ltr" style="text-align: left;font-family: Helvetica; margin-top: 25px;"> \
                        Best wishes and greetings,<br> \
                        Elise <br> \
                        Service Mapping Editor, Refugee.Info \
                    </p> \
                    </p>',
        type=NewsletterEmailTemplate.SERVICE_REMINDER,
        order=6
    ),
    dict(
        name='thanks_header_photo',
        label='Header photo',
        value='https://gallery.mailchimp.com/881109e97ad9515d9bad45d66/images/becee6c1-2301-4b0f-a898-1fb067842865.jpg',
        type=NewsletterEmailTemplate.SERVICE_THANKS,
        order=1
    ),
    dict(
        name='thanks_content_text',
        label='Content text',
        value=' \
            <p dir="ltr" style="text-align: left;font-family: Helvetica; margin-top: 0px;"> \
                Thank you for updating \
                us about your organization’s services! \
            </p> \
            <p dir="ltr" style="text-align: left;font-family: Helvetica;"> \
                By keeping us updated, \
                we can ensure that the users of our map can access accurate information \
                about their options. \
            </p> \
            <p dir="ltr" style="text-align: left;font-family: Helvetica;"> \
                I appreciate your help and look forward to being in touch again - we’ll \
                send another request for updates in about six weeks. If someone else \
                should be the focal point for these entries, please reply to this email \
                to let me know. \
            </p> \
            <p dir="ltr" style="text-align: left;font-family: Helvetica;"> \
                My thanks once more! \
            </p> \
            <p dir="ltr" style="text-align: left;font-family: Helvetica; margin-bottom: 17px;"> \
                Best wishes and greetings, <br> \
                Elise <br> \
                Service Mapping Editor, Refugee.Info \
            </p>',
        type=NewsletterEmailTemplate.SERVICE_THANKS,
        order=2
    )
]


def no_op(apps, schema_editor):
    pass


def create_email_html_inserts(apps, schema_editor):
    NewsletterEmailTemplate = apps.get_model('services', 'NewsletterEmailTemplate')
    for insert in INITIAL_EMAIL_HTML_INSERTS:
        NewsletterEmailTemplate.objects.update_or_create(
            name=insert['name'],
            defaults={
                "value": insert['value'],
                "label": insert['label'],
                "type": insert['type'],
                "order": insert['order']
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_auto_20170711_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterEmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('value', ckeditor.fields.RichTextField()),
                ('type', models.CharField(choices=[('service_base', 'service_base'), ('service_confirmation', 'service_base'), ('service_reminder', 'service_base'), ('service_thanks', 'service_base')], default='service_base', max_length=20, verbose_name='type')),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.RunPython(
            code=create_email_html_inserts,
            reverse_code=no_op,
            atomic=True
        ),
    ]
