# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-20 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_newsletteremailtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='newsletter_valid_email',
            new_name='newsletter_valid_emails',
        ),
        migrations.AddField(
            model_name='service',
            name='second_focal_point_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='second_focal_point_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='second_focal_point_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
