# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_auto_20170728_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='languages_spoken_ar',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Arabic'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_de',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in German'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_el',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Greek'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_en',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in English'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_es',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Spanish'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_fa',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Persian'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_fr',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in French'),
        ),
    ]
