# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 13:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_auto_20170802_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteremailtemplate',
            name='value',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
