# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-10 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0025_auto_20170705_1312'),
        ('services', '0046_auto_20170824_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='regions.GeographicRegion', verbose_name='Region'),
        ),
    ]
