# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-27 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_provider_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name in Urdu'),
        ),
        migrations.AddField(
            model_name='provider',
            name='address_ur',
            field=models.TextField(blank=True, default='', verbose_name='provider address in Urdu'),
        ),
        migrations.AddField(
            model_name='provider',
            name='description_ur',
            field=models.TextField(blank=True, default='', verbose_name='description in Urdu'),
        ),
        migrations.AddField(
            model_name='provider',
            name='focal_point_name_ur',
            field=models.CharField(blank=True, default='', max_length=256, validators=[services.models.blank_or_at_least_one_letter], verbose_name='focal point name in Urdu'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, validators=[services.models.blank_or_at_least_one_letter], verbose_name='Name in Urdu'),
        ),
        migrations.AddField(
            model_name='providertype',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Urdu'),
        ),
        migrations.AddField(
            model_name='selectioncriterion',
            name='text_ur',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_info_ur',
            field=models.TextField(blank=True, default='', verbose_name='Additional information in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_city_ur',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (city) in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='address_floor_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_ur',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (street) in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ur',
            field=models.TextField(blank=True, default='', verbose_name='Description in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages_spoken_ur',
            field=models.TextField(blank=True, default='', verbose_name='Languages spoken in Urdu'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Urdu'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Urdu'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='comments_ur',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='comments in Urdu'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name in Urdu'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='providers', to=settings.AUTH_USER_MODEL, verbose_name='Team'),
        ),
    ]
