# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0049_contactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('viber', 'Viber'), ('whatsapp', 'Whatsapp'), ('skype', 'Skype'), ('facebook_messenger', 'Facebook Messenger')], default=None, max_length=20, null=True),
        ),
    ]
