# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-27 18:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0050_contactinformation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='index',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
