# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0051_auto_20180227_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Service'),
        ),
    ]
