# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-28 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_auto_20180227_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_information', to='services.Service', verbose_name='Service'),
        ),
    ]
