# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_auto_20180307_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='is frozen'),
        ),
    ]
