# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-05 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0056_provider_is_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='provider',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='twitter'),
        ),
    ]
