# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-20 19:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='additional_info',
            field=models.TextField(blank=True, default='', verbose_name='additional_info'),
        ),
        migrations.AddField(
            model_name='provider',
            name='meta_population',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='meta population'),
        ),
        migrations.AddField(
            model_name='provider',
            name='record',
            field=models.TextField(blank=True, default='', verbose_name='record'),
        ),
        migrations.AddField(
            model_name='provider',
            name='requirement',
            field=models.TextField(blank=True, default='', verbose_name='requirement'),
        ),
        migrations.AddField(
            model_name='provider',
            name='service_types',
            field=models.ManyToManyField(blank=True, to='services.ServiceType', verbose_name='service types'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vacancy',
            field=models.BooleanField(default=False, verbose_name='vacancy'),
        ),
    ]
