# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-20 19:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0059_auto_20180420_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='meta_population',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='meta_population'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service_types',
            field=models.ManyToManyField(blank=True, to='services.ServiceType', verbose_name='service_types'),
        ),
    ]
