# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-20 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_auto_20180420_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='service_types',
        ),
    ]
