# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-20 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0061_remove_provider_service_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='service_types',
            field=models.ManyToManyField(blank=True, to='services.ServiceType', verbose_name='service_types'),
        ),
    ]
