# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0062_provider_service_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
