# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-07 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0064_auto_20180614_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
