# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-20 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0065_auto_20180707_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='focal_point_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='second_focal_point_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
