# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-31 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0066_auto_20180720_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Whatsapp number'),
        ),
    ]
