# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0028_geographicregion_site'),
        ('services', '0067_service_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.GeographicRegion')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType')),
            ],
        ),
        migrations.AddField(
            model_name='servicetype',
            name='ordering',
            field=models.ManyToManyField(blank=True, through='services.TypesOrdering', to='regions.GeographicRegion', verbose_name='ordering'),
        ),
    ]
