# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_user', '0005_auto_20160403_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
