# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_user', '0006_auto_20170125_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailuser',
            options={'permissions': (('services_analytics', 'Can view Services Analytics'), ('content_analytics', 'Can view Content Analytics'), ('visitors_analytics', 'Can view Visitors Analytics'), ('mobile_app_analytics', 'Can view Mobile App Analytics'), ('Social Media Analytics', 'Can view Social Media Analytics')), 'verbose_name': 'user'},
        ),
    ]
