# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_user', '0007_auto_20170126_1724'),
    ]

    operations = [
    ]
