# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_user', '0006_auto_20170126_1011'),
        ('email_user', '0008_auto_20170127_1010'),
    ]

    operations = [
    ]
