# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_user', '0009_merge_20170127_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailuser',
            options={'permissions': (('services_analytics', 'Can view Services Analytics'), ('content_analytics', 'Can view Content Analytics'), ('visitors_analytics', 'Can view Visitors Analytics'), ('mobile_app_analytics', 'Can view Mobile App Analytics'), ('social_media_analytics', 'Can view Social Media Analytics'), ('hotspots_analytics', 'Can view Hotspots Analytics'), ('balance_checker_analytics', 'Can view Balance Checker Analytics'), ('gas_search_tool_analytics', 'Can view Gas Search Tool Analytics'), ('unassigned_region_analytics', 'Can view Unassigned Region Analytics')), 'verbose_name': 'user'},
        ),
    ]
