# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_user', '0011_auto_20170130_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='google',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
