# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import email_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_user', '0012_auto_20170131_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=email_user.models.get_upload_path),
        ),
    ]
