# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 12:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_user', '0013_emailuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Invalid phone number', regex='(^[\\d+](?!.*--)[\\d-]{7,18}[\\d])$')]),
        ),
    ]
