# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-05 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0027_auto_20180307_2215'),
        ('email_user', '0014_auto_20170216_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='regions.GeographicRegion'),
        ),
    ]
