# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-05 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('email_user', '0015_emailuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sites.Site'),
        ),
    ]
