# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-03 20:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import regions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_index', models.IntegerField(blank=True, null=True)),
                ('content_slug', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbs_up', models.PositiveIntegerField(default=0)),
                ('thumbs_down', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GeographicRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Country'), (2, 'Region'), (3, 'City')])),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(default='', max_length=256)),
                ('slug', models.CharField(default='', max_length=100)),
                ('code', models.CharField(blank=True, max_length=16)),
                ('hidden', models.BooleanField(default=False)),
                ('languages_available', models.CharField(blank=True, help_text='Comma separated values of languages available in this region', max_length=300)),
                ('restrict_access_to', models.TextField(blank=True, help_text='Comma separated values of code of siblings visible from this region', null=True)),
                ('title_en', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in English')),
                ('title_ar', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Arabic')),
                ('title_fa', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Persian')),
                ('title_fr', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in French')),
                ('title_de', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in German')),
                ('title_el', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Greek')),
                ('title_ur', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Urdu')),
                ('title_es', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Spanish')),
                ('title_ti', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Tigrinya')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='regions.GeographicRegion')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sites.Site')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
            bases=(models.Model, regions.models.ContentFetchingMixin),
        ),
        migrations.CreateModel(
            name='ImportantInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, help_text='Used to sort the important information', max_length=16)),
                ('icon', models.CharField(blank=True, max_length=256, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('title_en', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in English')),
                ('title_ar', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Arabic')),
                ('title_fa', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Persian')),
                ('title_fr', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in French')),
                ('title_de', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in German')),
                ('title_el', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Greek')),
                ('title_ur', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Urdu')),
                ('title_es', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Spanish')),
                ('title_ti', models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Tigrinya')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='regions.GeographicRegion')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, regions.models.ContentFetchingMixin),
        ),
        migrations.CreateModel(
            name='IPGeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('geoname_id', models.IntegerField(default=0)),
                ('registered_country_geoname_id', models.IntegerField(default=0)),
                ('represented_country_geoname_id', models.IntegerField(default=0)),
                ('is_anonymous_proxy', models.NullBooleanField(default=False)),
                ('is_satellite_provider', models.NullBooleanField(default=False)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=14, default=0, max_digits=17, null=True)),
                ('longitude', models.DecimalField(decimal_places=14, default=0, max_digits=17, null=True)),
                ('type', models.CharField(choices=[('v4', 'IPV4'), ('v6', 'IPV6')], default='v4', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='contentrate',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.GeographicRegion'),
        ),
        migrations.AlterUniqueTogether(
            name='contentrate',
            unique_together=set([('region', 'content_index', 'content_slug')]),
        ),
    ]
