# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_ipgeolocation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicregion',
            name='restrict_access_to',
            field=models.TextField(blank=True, help_text='Comma separated values of code of sibilings visible from this region', null=True),
        ),
    ]
