# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_geographicregion_restrict_access_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipgeolocation',
            name='network',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
