# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_auto_20160502_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicregion',
            options={'ordering': ['level', 'name_en']},
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='name',
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Arabic'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in German'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='name_el',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Greek'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in English'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Spanish'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='name_fa',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in Persian'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name in French'),
        ),
    ]
