# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0008_auto_20160502_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicregion',
            name='languages_available',
            field=models.CharField(blank=True, help_text='Comma separated values of languages available in this region', max_length=300),
        ),
        migrations.AlterField(
            model_name='geographicregion',
            name='restrict_access_to',
            field=models.TextField(blank=True, help_text='Comma separated values of code of siblings visible from this region', null=True),
        ),
    ]
