# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0009_auto_20160503_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicregion',
            options={'ordering': ['level', 'name']},
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='name_el',
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='name_fa',
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='name_fr',
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
