# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0010_auto_20160503_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicregion',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
