# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import regions.models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0011_geographicregion_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=16)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='important_information', to='regions.GeographicRegion')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, regions.models.ContentFetchingMixin),
        ),
    ]
