# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0012_importantinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicregion',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Arabic'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='title_de',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in German'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='title_el',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Greek'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in English'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='title_es',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Spanish'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='title_fa',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Persian'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='title_fr',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in French'),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Arabic'),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='title_de',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in German'),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='title_el',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Greek'),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in English'),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='title_es',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Spanish'),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='title_fa',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Persian'),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='title_fr',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in French'),
        ),
    ]
