# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0013_auto_20160718_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantinformation',
            name='icon',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
