# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0014_importantinformation_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantinformation',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
