# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0015_importantinformation_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinformation',
            name='code',
            field=models.CharField(blank=True, help_text='Used to sort the important information', max_length=16),
        ),
    ]
