# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0016_auto_20160722_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_index', models.IntegerField(blank=True, null=True)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('thumbs_down', models.IntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.GeographicRegion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contentrate',
            unique_together=set([('region', 'content_index')]),
        ),
    ]
