# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0017_auto_20160915_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrate',
            name='content_slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contentrate',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.GeographicRegion'),
        ),
        migrations.AlterField(
            model_name='contentrate',
            name='thumbs_down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contentrate',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='contentrate',
            unique_together=set([('region', 'content_index', 'content_slug')]),
        ),
    ]
