# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0018_auto_20160921_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinformation',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='regions.GeographicRegion'),
        ),
    ]
