# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0019_auto_20161215_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_base_url', models.URLField(blank=True, null=True)),
                ('web_base_url', models.URLField(blank=True, null=True)),
                ('light_base_url', models.URLField(blank=True, null=True)),
                ('name_en', models.CharField(blank=True, default='', max_length=256, verbose_name='name in English')),
                ('name_ar', models.CharField(blank=True, default='', max_length=256, verbose_name='name in Arabic')),
                ('name_fa', models.CharField(blank=True, default='', max_length=256, verbose_name='name in Persian')),
                ('name_fr', models.CharField(blank=True, default='', max_length=256, verbose_name='name in French')),
                ('name_de', models.CharField(blank=True, default='', max_length=256, verbose_name='name in German')),
                ('name_el', models.CharField(blank=True, default='', max_length=256, verbose_name='name in Greek')),
                ('name_es', models.CharField(blank=True, default='', max_length=256, verbose_name='name in Spanish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='apps',
            field=models.ManyToManyField(related_name='regions', to='regions.MicroApp'),
        ),
    ]
