# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('regions', '0021_microapp_admins'), ('regions', '0022_auto_20170126_1622')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0020_auto_20170121_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='microapp',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='apps', related_query_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
