# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import regions.models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0020_auto_20170121_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='microapp',
            name='api_base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microapp',
            name='authentication_token',
            field=models.CharField(blank=True, default=regions.models.default_authentication_token, max_length=50, null=True),
        ),
    ]
