# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0021_auto_20170126_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='microapp',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
