# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0021_microapp_admins_squashed_0022_auto_20170126_1622'),
        ('regions', '0022_microapp_slug'),
    ]

    operations = [
    ]
