# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0024_auto_20170201_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicregion',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='geographicregion',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
