# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0025_auto_20170705_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicregion',
            name='title_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Urdu'),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='title_ur',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Urdu'),
        ),
    ]
