# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0026_auto_20180227_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicregion',
            name='title_ti',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Tigrinya'),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='title_ti',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Title in Tigrinya'),
        ),
    ]
