# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-03 17:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0028_geographicregion_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicregion',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
