# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-08 12:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=255, verbose_name='phone')),
                ('categoryId', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='categoryId')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('validationCode', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
            ],
        ),
    ]
