# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-09-13 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('validationCode', models.CharField(blank=True, default='', max_length=255)),
                ('expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
