# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='validationCode',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
