# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20191108_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='categoryId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category'),
        ),
    ]
