# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-08 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20191108_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=set([('phone', 'categoryId')]),
        ),
    ]
