# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20191108_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='categoryId',
            field=models.CharField(max_length=255, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='phone'),
        ),
    ]
