# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-26 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20191126_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(blank=True, max_length=255)),
                ('body', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=15)),
                ('error_code', models.CharField(blank=True, max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('from_number', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('price_unit', models.CharField(blank=True, max_length=255)),
                ('sid', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('to', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
