# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-26 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_messagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='error_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
